### ISSUE TITLE
Volunteer Calendar - "one-off" time slots

### ISSUE THREAD

**Issue by rastographics** [bvcms/bvcms#116] opened 2016-05-04 17:17 UTC
So at this time there is no way to add an "extra" time-slot for a volunteer calendar. 

**Use Case:**
We have media team Org with 3 weekly volunteer timeslots. Would be great for weddings, concerts, special events and services, etc. to be able to just add another "date-specific" time-slot to the calendar.

These special events are really the ones that would be the most helpful for us to use the volunteering features, because they require us asking all the volunteers who can fill them since they aren't in regular weekly schedule.

I would like to investigate further and determine if there is a non-invasive way to implement this through an extra-value and/or setting. @davidcarroll  any thoughts/warnings on this?

**Comment by davidcarroll** [comment] 2016-05-04 17:32
There is another project on the list to rewrite the volunteer calendar. This would have to be part of that project. The project is still in the investigation phase on what all we want it to be able to do. There are a lot of features besides the one you mentioned that we want to add.

The hangup I see with supporting ad-hoc meetings is that they won't fit with how we have this implemented and would require a total rethink and architecture. We have a very structured view of the current volunteer calendar that only understands scheduled time slots with no room for ad-hoc slots outside the matrix of weeks and times. 

It works well for the purpose it was designed for. Our first use case was to handle pre-school volunteers who commit for a particular week of the month and should be able to request substitutes without having to ask the leader to do it for them. It puts the responsibility on the volunteer to find their own substitute by giving the means to do so using the system. Anything beyond that like ad-hoc meetings and scheduling volunteers for particular jobs like praise band parts, etc. are completely outside the scope of the original use case.

I am going to close this as an issue since the issue will be resolved with current project plans over the next year or so, but you are welcome to continue to comment.

**Closed by davidcarroll** 2016-05-04 17:32 UTC

**Comment by rastographics** [comment] 2016-05-04 17:57
OK sounds good. As you mention, attaching "notes" or "assignments" per volunteer per slot is another feature I was thinking of that would be super functional.

Do you have some sort of project list that you are willing to make accessible to developers looking to contribute?

**Comment by davidcarroll** [comment] 2016-05-04 18:09
I just gave you access to our Trello Development board

**Comment by rastographics** [comment] 2016-05-09 04:39
Thanks very much. Do you mind if I comb through the trello discussions on this topic and give input through the trello comments?

**Comment by davidcarroll** [comment] 2016-05-09 05:31
No problem.
